### ISSUE TITLE
Forge 1.14

### ISSUE THREAD

**Issue by langeover** [SDUBZ/Launcher#1]
Hi i just have a question, you want to make compatible forge 1.14/1.13 with this launcher pack ?
or else how do we install fabric ?

sorry for my bad english i'm french 

bye and thanks

**Comment by SDUBZ** [comment]
both are incompatible atm until the package constructor gets tweaked further

**Comment by langeover** [comment]
Ok thanks, and you know when he will put that in place ?

**Comment by SDUBZ** [comment]
as of now im not sure
